### ISSUE TITLE
判別結果のポケモンを訂正するときに進化元のアローラのすがたをリストから選択するとアプリが落ちる

### ISSUE THREAD

**Issue by udnp** [udnp/GoIV_JP#28]
例えば，ポケモン「アローラのすがたのベトベトン」に対して，
訂正ダイアログで「アローラのすがたのベトベター」を進化系列リストから選択すると，
次の exception で落ちる．

```
06-27 09:12:19.951 14642-14642/nagoya.sawdagger.pogoiv.nointernet.debug E/AndroidRuntime: FATAL EXCEPTION: main
    Process: nagoya.sawdagger.pogoiv.nointernet.debug, PID: 14642
    java.lang.IndexOutOfBoundsException: Index: 2, Size: 2
        at java.util.ArrayList.get(ArrayList.java:411)
        at com.kamron.pogoiv.Pokefly.initPokemonSpinnerIfNeeded(Pokefly.java:1632)
        at com.kamron.pogoiv.Pokefly.populateAdvancedInformation(Pokefly.java:1442)
        at com.kamron.pogoiv.Pokefly.populateResultsBox(Pokefly.java:1282)
        at com.kamron.pogoiv.Pokefly.checkIv(Pokefly.java:1053)
        at com.kamron.pogoiv.Pokefly_ViewBinding$12.doClick(Pokefly_ViewBinding.java:226)
        at butterknife.internal.DebouncingOnClickListener.onClick(DebouncingOnClickListener.java:22)
        at android.view.View.performClick(View.java:5685)
        at android.view.View$PerformClick.run(View.java:22481)
        at android.os.Handler.handleCallback(Handler.java:751)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:241)
        at android.app.ActivityThread.main(ActivityThread.java:6274)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
```

**Comment by udnp** [comment]
`com/kamron/pogoiv/scanlogic/PokeInfoCalculator.java`
```java
    public ArrayList<Pokemon> getEvolutionLine(Pokemon poke) {
        poke = getLowestEvolution(poke);
 
        ArrayList<Pokemon> list = new ArrayList<>();
        list.addAll(getForms(poke));
        for (Pokemon evolution2nd : poke.evolutions) {
```
poke がアローラのすがたのポケモンだった場合に，
この箇所で `poke.evolutions` が empty な ArrayList になってしまっている．

**Comment by udnp** [comment]
本家の v5.0.8 でも同根の問題が発生しているが，
exception を catch しているのか落ちることはない．

訂正ダイアログでアローラのすがたの進化元のポケモン (アローラのニャース) に，
進化先のポケモン (アローラのペルシアン) が表示されない．
![device-2018-06-28-153706](https://user-images.githubusercontent.com/17121615/42017744-1633bda8-7aeb-11e8-95b0-e1f1ca718ecd.png)

**Comment by udnp** [comment]
次の commit で修正した．
https://github.com/udnp/GoIV_JP/commit/c8ae9dbb81eacf15793e98f6e3122381d3a3b778

本家にも修正 patch の PR を出して採用された．
https://github.com/farkam135/GoIV/pull/949/files
